version: "3.8"

services:
  yaniv-server:
    build: .
    container_name: yaniv-server
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npx nodemon server.js
