version: "3.8"

services:
  yaniv-server:
    build: .
    container_name: yaniv-server
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npx nodemon server.js

  yaniv-frontend:
    build: ./frontend
    container_name: yaniv-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - yaniv-server
